### PR TITLE
fix: model author removal bug in garden metadata

### LINKED ISSUE #353: Removing gardeners or model authors shows success message, but doesn't update correctly
https://github.com/user-attachments/assets/24f51fff-7fd5-4368-ac89-95f961dfce4c

### PR DESCRIPTION
**Pull request by hholb**
Resolves: #353 

This PR fixes a bug where removing an author from a garden's metadata would display a success message, but the author list was not updated correctly. This also fixes a related issue that was causing duplicate gardeners to appear that could not be removed.

Error handling and messaging to user when they attempt to remove all authors and contributors from a garden are improved.

**Before**

https://github.com/user-attachments/assets/ea698ae2-edfa-4ac7-8ea0-551bcd0208c7

**After**

https://github.com/user-attachments/assets/82c144e7-5695-4b5e-a8d8-8dc9ce6f6261

**Explicit handling of missing authors and contributors**

https://github.com/user-attachments/assets/0fabaf22-0761-4379-88a3-e00b519997e6

## Discussion

There was an issue with the multiple selector component not calling the `onUpdate` handler to when removing all items from the input.

## Testing
Manually

### CODE REVIEW

File: garden/src/features/gardens/api/usePatchGarden.ts [hunk 1]
```diff
@@ -56,11 +56,13 @@ export const usePatchGarden = () => {
       return { previousGarden };
     },
     onError: (err, { doi }, context) => {
-      // If the mutation fails, use the context to roll back
-      if (context?.previousGarden) {
-        queryClient.setQueryData(["garden", doi], context.previousGarden);
+      console.error(err.message)
+      if (err.message.includes("409")) {
+        toast.error(`Failed to update garden: Garden must have at least one Model Author or one Gardener`);
```
Comment (OwenPriceSkelly) [inline garden/src/features/gardens/api/usePatchGarden.ts:61]: is there an easy way to have this just be the `detail` part of the response? since we're returning the same message from the backend anyway

**Review by OwenPriceSkelly — APPROVED** [review]
LGTM
